[project]
name = "mcp-demo"
version = "0.1.0"
description = "MCP Demo"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.6.0",
    "fastapi>=0.104.0",
    "uvicorn>=0.23.2",
    "pydantic>=2.4.2",
    "openai>=1.3.0",
]